

- name: Create Terraform directory
  file:
    path: "{{terraform_dir}}"
    state: directory
  register: terraform_directory

- name: check terraform version
  shell: "terraform version 2>&1 | head -n 1 | grep -q {{terraform_version}}"
  failed_when: false
  changed_when: false
  register: terraform_versions_match

- name: Download terraform linux 64 bits
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /tmp/terraform-{{ terraform_version }}.zip

- name: Install unzip to unarchive terraform
  package:
    name: unzip
    state: present

- name: Unarchive Terraform archive
  unarchive:
    src: /tmp/terraform-{{terraform_version}}.zip
    dest: "{{ terraform_dir }}"
    copy: no

- name: Add terraform to command path
  file:
    src: "{{terraform_dir}}/terraform"
    dest: /usr/bin/terraform
    state: link

