version: "3"

services:
        # MQTT broker
        broker:
                container_name: broker
                image: toke/mosquitto
                ports:
                        - "1883:1883"

        # GPS coords source
        source_gps:
                container_name: source_gps
                image: mclarenappliedtechnologies/recruitment.fanengagement.streamgenerator
                links:
                        - broker
                env_file:
                        - ./source_gps.env
                        - ./mqtt.env
                        - ./cars.env
                ports:
                        - "8081:8080"

        # Write to websocket
        mqtt_to_websocket:
                container_name: mqtt-to-websocket
                image: mclarenappliedtechnologies/recruitment.fanengagement.forwarder
                links:
                        - broker
                env_file:
                        - ./mqtt.env
                ports:
                        - "8080:8080"


        # Webapp
        webapp:
                container_name: webapp
                image: mclarenappliedtechnologies/recruitment.fanengagement.webapp
                links:
                        - mqtt_to_websocket
                ports:
                        - "8084:8084"

        processapp:

                container_name: processapp
                image: processapp
                build: ./processapp
                ports:
                        - "5000:5000"

        influxdb:
                image: influxdb:latest
                container_name: influxdb
                ports:
                        - "8086:8086"
                volumes: 
                        - /data/influxdb-storage:/var/lib/influxdb

                environment:
                        - INFLUXDB_DB="mclarenDB"
                        - INFLUXDB_ADMIN_USER="admin"
                        - INFLUXDB_PASSWORD="admin"
                               





