apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: broker
  ports: 
  - protocol: TCP
    port: 1883
    targetPort: 1883
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels: 
    app: broker
spec:
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker 
        image: toke/mosquitto
        env:
        - name: MQTT_URL
          value: tcp://broker:1883
        - name: MQTT_TOPIC
          value: carCoordinates  
        ports:
        - containerPort: 1883
