apiVersion: v1
kind: Service
metadata:
  name: source-gps
spec:
  selector:
    app: source-gps
  ports: 
  - protocol: TCP
    port: 8081
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-gps
  labels: 
    app: source-gps
spec:
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: source-gps
  template:
    metadata:
      labels:
        app: source-gps
    spec:
      containers:
      - name: source-gps 
        image: mclarenappliedtechnologies/recruitment.fanengagement.streamgenerator
        env:
        - name: MQTT_URL
          value: tcp://broker:1883
        - name: MQTT_TOPIC
          value: carCoordinates
        - name: CAR_COUNT
          value: "6"
        - name: LOOP_DELAY
          value: "200"
        ports:
        - containerPort: 8081
