apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports: 
  - protocol: TCP
    port: 8084
    targetPort: 8084
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels: 
    app: webapp
spec:
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp 
        image: mclarenappliedtechnologies/recruitment.fanengagement.webapp
        ports:
        - containerPort: 8084
